use HIGH_AGE_CD;
select 
D_FUNC_BIR.ID_SEX,
DATEDIFF(DAY, D_FUNC_BIR.F_D_DATE,FIRST_CANCER.F_D_DATE) as datedif,
DATEDIFF(YEAR, D_FUNC_BIR.NEW_BIRTHDAY,D_FUNC_BIR.F_D_DATE) as age
from D_FUNC_BIR
inner join FIRST_CANCER
on D_FUNC_BIR.ID = FIRST_CANCER.ID
where
(FIRST_CANCER.F_D_DATE>D_FUNC_BIR.F_D_DATE)