DECLARE @A INT
DECLARE @T NVARCHAR(2)
DECLARE @AGE NVARCHAR(3)
SET @AGE = 'AGE'
SET @T = '1'
SET @A = 2003
WHILE @A <= 2003
BEGIN

EXEC('
SELECT HIGH_AGE_CD.DBO.CD'+@A+'.ID, HIGH_AGE_CD.DBO.CD'+@A+'.FUNC_DATE,
	   HIGH_AGE_ID.DBO.UID'+@A+'.ID_BIRTHDAY, HIGH_AGE_ID.DBO.UID'+@A+'.ID_SEX,
	   ROUND(DATEDIFF(DAY, HIGH_AGE_ID.DBO.UID'+@A+'.ID_BIRTHDAY, HIGH_AGE_CD.DBO.CD'+@A+'.FUNC_DATE)/365.25, 0) AS '+@AGE+'
FROM HIGH_AGE_CD.DBO.CD'+@A+'
LEFT JOIN HIGH_AGE_ID.DBO.UID'+@A+'
ON HIGH_AGE_CD.DBO.CD'+@A+'.ID = HIGH_AGE_ID.DBO.UID'+@A+'.ID
WHERE (ISDATE(HIGH_AGE_ID.DBO.UID'+@A+'.ID_BIRTHDAY) = '+@T+' AND ISDATE(HIGH_AGE_CD.DBO.CD'+@A+'.FUNC_DATE) = '+@T+') AND HIGH_AGE_ID.DBO.UID'+@A+'.ID_SEX = ''F'';
')

EXEC('
SELECT HIGH_AGE_CD.DBO.CD'+@A+'.ID, HIGH_AGE_CD.DBO.CD'+@A+'.FUNC_DATE,
	   HIGH_AGE_ID.DBO.UID'+@A+'.ID_BIRTHDAY, HIGH_AGE_ID.DBO.UID'+@A+'.ID_SEX,
	   ROUND(DATEDIFF(DAY, HIGH_AGE_ID.DBO.UID'+@A+'.ID_BIRTHDAY, HIGH_AGE_CD.DBO.CD'+@A+'.FUNC_DATE)/365.25, 0) AS '+@AGE+'
FROM HIGH_AGE_CD.DBO.CD'+@A+'
LEFT JOIN HIGH_AGE_ID.DBO.UID'+@A+'
ON HIGH_AGE_CD.DBO.CD'+@A+'.ID = HIGH_AGE_ID.DBO.UID'+@A+'.ID
WHERE (ISDATE(HIGH_AGE_ID.DBO.UID'+@A+'.ID_BIRTHDAY) = '+@T+' AND ISDATE(HIGH_AGE_CD.DBO.CD'+@A+'.FUNC_DATE) = '+@T+') AND HIGH_AGE_ID.DBO.UID'+@A+'.ID_SEX = ''M'';
')

EXEC('
SELECT HIGH_AGE_CD.DBO.CD'+@A+'.ID, HIGH_AGE_CD.DBO.CD'+@A+'.FUNC_DATE,
	   HIGH_AGE_ID.DBO.UID'+@A+'.ID_BIRTHDAY, HIGH_AGE_ID.DBO.UID'+@A+'.ID_SEX,
	   ROUND(DATEDIFF(DAY, HIGH_AGE_ID.DBO.UID'+@A+'.ID_BIRTHDAY, HIGH_AGE_CD.DBO.CD'+@A+'.FUNC_DATE)/365.25, 0) AS '+@AGE+'
FROM HIGH_AGE_CD.DBO.CD'+@A+'
LEFT JOIN HIGH_AGE_ID.DBO.UID'+@A+'
ON HIGH_AGE_CD.DBO.CD'+@A+'.ID = HIGH_AGE_ID.DBO.UID'+@A+'.ID
WHERE (ISDATE(HIGH_AGE_ID.DBO.UID'+@A+'.ID_BIRTHDAY) = '+@T+' AND ISDATE(HIGH_AGE_CD.DBO.CD'+@A+'.FUNC_DATE) = '+@T+') AND HIGH_AGE_ID.DBO.UID'+@A+'.ID_SEX = ''U'';
')

SET @A = @A + 1
END