USE HIGH_AGE_CD
SELECT * INTO TEST FROM CD2005

UPDATE TEST
SET AGE = CONVERT(INT, SUBSTRING(FUNC_DATE, 1, 4)) - CONVERT(INT,SUBSTRING(ID_BIRTHDAY, 1, 4))


SELECT ID,
(
  SELECT TOP 1 AGE_2
  FROM  HIGH_AGE_ID.DBO.ID2005 AS T2
  WHERE T2.ID = T1.ID
  GROUP BY AGE_2
) AS [AGE_2]
FROM HIGH_AGE_ID.DBO.ID2005 AS T1
where AGE_2<=70 and age_2>60
GROUP BY ID