USE HIGH_AGE_ID;

WITH B AS(
SELECT ID, ID_BIRTHDAY FROM ID2003
UNION ALL
SELECT ID, ID_BIRTHDAY FROM ID2004
UNION ALL
SELECT ID, ID_BIRTHDAY FROM ID2005
UNION ALL
SELECT ID, ID_BIRTHDAY FROM ID2006
UNION ALL
SELECT ID, ID_BIRTHDAY FROM ID2007
UNION ALL
SELECT ID, ID_BIRTHDAY FROM ID2008
UNION ALL
SELECT ID, ID_BIRTHDAY FROM ID2009
UNION ALL
SELECT ID, ID_BIRTHDAY FROM ID2010
UNION ALL
SELECT ID, ID_BIRTHDAY FROM ID2011
UNION ALL
SELECT ID, ID_BIRTHDAY FROM ID2012
UNION ALL
SELECT ID, ID_BIRTHDAY FROM ID2013)
SELECT * INTO ID_ALL
FROM B
GROUP BY ID, ID_BIRTHDAY
ORDER BY ID;

SELECT * FROM ID_ALL
WHERE ID IN(
SELECT ID FROM ID_ALL
GROUP BY ID
HAVING COUNT(*)>1)
ORDER BY ID