USE HIGH_AGE_DD
declare @i int
set @i=1996
while @i<=2013
begin 

EXEC('
SELECT *
INTO RRDD'+@i+'
FROM RDD'+@i+'01
UNION ALL
SELECT *
FROM RDD'+@i+'02
UNION ALL
SELECT *
FROM RDD'+@i+'03
UNION ALL
SELECT *
FROM RDD'+@i+'04
UNION ALL
SELECT *
FROM RDD'+@i+'05
UNION ALL
SELECT *
FROM RDD'+@i+'06
UNION ALL
SELECT *
FROM RDD'+@i+'07
UNION ALL
SELECT *
FROM RDD'+@i+'08
UNION ALL
SELECT *
FROM RDD'+@i+'09
UNION ALL
SELECT *
FROM RDD'+@i+'10
UNION ALL
SELECT *
FROM RDD'+@i+'11
UNION ALL
SELECT *
FROM RDD'+@i+'12
')
    
set @i=@i+1
end

USE HIGH_AGE_DD
declare @J int
set @J=1996
while @J<=2013
begin 
/*
EXEC('DROP TABLE RDD'+@J+'01')
EXEC('DROP TABLE RDD'+@J+'02')
EXEC('DROP TABLE RDD'+@J+'03')
EXEC('DROP TABLE RDD'+@J+'04')
EXEC('DROP TABLE RDD'+@J+'05')
EXEC('DROP TABLE RDD'+@J+'06')
EXEC('DROP TABLE RDD'+@J+'07')
EXEC('DROP TABLE RDD'+@J+'08')
EXEC('DROP TABLE RDD'+@J+'09')
EXEC('DROP TABLE RDD'+@J+'10')
EXEC('DROP TABLE RDD'+@J+'11')
EXEC('DROP TABLE RDD'+@J+'12')
*/
EXEC('DROP TABLE RRDD'+@J+'01')
EXEC('DROP TABLE RRDD'+@J+'02')
EXEC('DROP TABLE RRDD'+@J+'03')
EXEC('DROP TABLE RRDD'+@J+'04')
EXEC('DROP TABLE RRDD'+@J+'05')
EXEC('DROP TABLE RRDD'+@J+'06')
EXEC('DROP TABLE RRDD'+@J+'07')
EXEC('DROP TABLE RRDD'+@J+'08')
EXEC('DROP TABLE RRDD'+@J+'09')
EXEC('DROP TABLE RRDD'+@J+'10')
EXEC('DROP TABLE RRDD'+@J+'11')
EXEC('DROP TABLE RRDD'+@J+'12')

set  @J=@J+1
end
