WITH A AS(
SELECT ID, ID_SEX, NEW_BIRTHDAY FROM HIGH_AGE_ID.DBO.NEW_UID2003
UNION ALL
SELECT ID, ID_SEX, NEW_BIRTHDAY FROM HIGH_AGE_ID.DBO.NEW_UID2004
UNION ALL
SELECT ID, ID_SEX, NEW_BIRTHDAY FROM HIGH_AGE_ID.DBO.NEW_UID2005
UNION ALL
SELECT ID, ID_SEX, NEW_BIRTHDAY FROM HIGH_AGE_ID.DBO.NEW_UID2006
UNION ALL
SELECT ID, ID_SEX, NEW_BIRTHDAY FROM HIGH_AGE_ID.DBO.NEW_UID2007
UNION ALL
SELECT ID, ID_SEX, NEW_BIRTHDAY FROM HIGH_AGE_ID.DBO.NEW_UID2008
UNION ALL
SELECT ID, ID_SEX, NEW_BIRTHDAY FROM HIGH_AGE_ID.DBO.NEW_UID2009
UNION ALL
SELECT ID, ID_SEX, NEW_BIRTHDAY FROM HIGH_AGE_ID.DBO.NEW_UID2010
UNION ALL
SELECT ID, ID_SEX, NEW_BIRTHDAY FROM HIGH_AGE_ID.DBO.NEW_UID2011
UNION ALL
SELECT ID, ID_SEX, NEW_BIRTHDAY FROM HIGH_AGE_ID.DBO.NEW_UID2012
UNION ALL
SELECT ID, ID_SEX, NEW_BIRTHDAY FROM HIGH_AGE_ID.DBO.NEW_UID2013
)
SELECT DISTINCT * INTO HIGH_AGE_ID.DBO.NEW_ID100W FROM A
