USE HIGH_AGE_ID

DECLARE @I INT
DECLARE @J NVARCHAR(15)
SET @I = 2002
SET @J = '15'
WHILE @I <= 2013
BEGIN

-- 1. 以入保日期排序，最接近現在的code=1
EXEC('
SELECT ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID_IN_DATE DESC) AS CODE, ID, ID_SEX, ID_BIRTHDAY
INTO TABLED
FROM [ID'+@I+']
')

-- 2. 挑選最新的一筆當作是正確的資料
EXEC('
SELECT ID,ID_SEX,ID_BIRTHDAY
INTO UID'+@I+'
FROM TABLED
WHERE CODE = ''1'' and ID in (select ID from ID'+@I+')
')
EXEC('
UPDATE UID'+@I+'
SET ID_BIRTHDAY = SUBSTRING(ID_BIRTHDAY, 1, 6);
UPDATE UID'+@I+'
SET ID_BIRTHDAY = CONCAT(ID_BIRTHDAY, '+@J+');
')

/*處理ID_SEX奇怪的變數*/
EXEC('
UPDATE UID'+@I+'
SET ID_SEX = ''U''
WHERE ID_SEX <> ''M'' AND 
      ID_SEX <> ''F'' 
')

EXEC('DROP TABLE TABLED')

SET @I = @I +1
END