select 
UID100W.ID, UID100W.ID_SEX, SUBSTRING(UID100W.NEW_BIRTHDAY, 1, 4) as BIR_YEAR,
FIRST_DIABETES.F_D_DATE, SUBSTRING(FIRST_DIABETES.F_D_DATE, 1, 4) as F_D_YEAR, ROUND(DATEDIFF(DAY, UID100W.NEW_BIRTHDAY, FIRST_DIABETES.F_D_DATE)/365.25, 0) as F_D_AGE,
FIRST_CANCER_SP.F_C_DATE, SUBSTRING(FIRST_CANCER_SP.F_C_DATE, 1, 4) as F_C_YEAR, ROUND(DATEDIFF(DAY, UID100W.NEW_BIRTHDAY, FIRST_CANCER_SP.F_C_DATE)/365.25, 0) as F_C_AGE,
death_all.death_year, convert(int, death_all.death_year) - convert(int, SUBSTRING(UID100W.NEW_BIRTHDAY, 1, 4)) as DEATH_AGE
into new.dbo.UID_D_C_SP_DEATH
from HIGH_AGE_ID.dbo.UID100W
left join HIGH_AGE_CD.dbo.FIRST_DIABETES
on UID100W.ID = FIRST_DIABETES.ID
left join HIGH_AGE_CD.dbo.FIRST_CANCER_SP
on UID100W.ID = FIRST_CANCER_SP.ID
left join HIGH_AGE_ID.dbo.death_all
on UID100W.ID = death_all.id